Add new examples of helm configuration
DelineaXPM/dsv-k8s pull request #119
Opened 2024-04-26 10:12 UTC by Tosta-Mista

Hello, 

This PR to add new documentation examples. 

Issue: #118

2024-04-26 14:05 UTC, pacificcode approved these changes
LGTM

2024-06-06 21:01 UTC, sheldonhull requested changes
minor quick changes. greatly appreciate the contribution!

2024-06-06 21:01 UTC, sheldonhull commented on docs/configure.md
> +    "tld": "eu"
Can you revert the changes for the code sample since it's already included in the linked docs? Appreciate it!

2024-06-08 00:33 UTC, closed without merging

2024-06-08 00:34 UTC, sheldonhull commented
to avoid delay/reworking, I went ahead and got the change in, so definitely appreciate bringing up that it wasn't clear enough. cheers!